spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG

app:
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}
    swagger-enabled: ${SWAGGER_ENABLED:true}