server:
  port: ${PORT:9090}

app:
  crypto:
    evolucao-key: ${CRYPTO_KEY}
  secret: ${APP_SECRET}
  timezone: ${APP_TIMEZONE:America/Fortaleza}
  bootstrap:
    admin:
      enabled: ${ADMIN_BOOTSTRAP_ENABLED:false}
      name: ${ADMIN_NAME:}
      email: ${ADMIN_EMAIL:}
      password: ${ADMIN_PASSWORD:}

spring:
  application:
    name: "gestao_psicologica"
  jackson:
    time-zone: ${app.timezone}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          timezone: ${app.timezone}

springdoc:
  api-docs:
    enabled: ${app.security.swagger-enabled:false}
  swagger-ui:
    enabled: ${app.security.swagger-enabled:false}

google:
  cliente-id: ${GOOGLE_CLIENTE_ID}