spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: INFO

app:
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
    swagger-enabled: ${SWAGGER_ENABLED:false}
